### ISSUE TITLE
Improve contrast

### ISSUE THREAD

**Issue by markushaslinger** [Jonas-Pamminger/WMC_ARWebsite#14]
The contrast of text and background is not optimal, especially when scrolling down

**Comment by schramls** [comment]
hmm, still not happy with the contrast, esp. the blueish text on green-blue background.
If you really wanna stick to this design, because you find it so beautiful: Fine for me BUT ADD an high contrast theme (a second color CSS using high contract colors and fonts) -> switch via NavBar
